app:
  replicas: 1
  port: 3000
  image:
    repository: 211125331032.dkr.ecr.eu-west-1.amazonaws.com/jtk-ops-hub-v2
    tag: b717f928aa55625e2dafa49ff7cf7f2c64df8be0
    pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  host: jtk-ops-hub-v2.dp.com
  aliasHost: jtk.dp.com

sandboxName: jtk-ops-hub-v2

database:
  enabled: true

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

serviceAccount:
  create: true
  name: ""
  annotations: {}


externalSecret:
  storeKind: ClusterSecretStore
  storeName: aws-secrets-manager
  secretPath: jtk-ops-hub-v2
  refreshInterval: 5m

s3:
  enabled: false

publicIngress:
  enabled: false

redis:
  enabled: false

jobsRbac:
  enabled: false
