{{- if .Values.argocd.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.sandboxName }}
  namespace: {{ .Values.argocd.namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ .Values.sandboxName }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    sandbox.deel/name: {{ .Values.sandboxName }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argocd.project }}
  source:
    repoURL: {{ .Values.argocd.repoURL | quote }}
    targetRevision: {{ .Values.argocd.targetRevision | quote }}
    path: {{ .Values.argocd.path | quote }}
    {{- if or .Values.argocd.helm.valueFiles .Values.argocd.helm.values }}
    helm:
      {{- if .Values.argocd.helm.valueFiles }}
      valueFiles:
        {{- toYaml .Values.argocd.helm.valueFiles | nindent 8 }}
      {{- end }}
      {{- if .Values.argocd.helm.values }}
      values: |
        {{- .Values.argocd.helm.values | nindent 8 }}
      {{- end }}
    {{- end }}

  destination:
    server: "https://kubernetes.default.svc"
    namespace: {{ .Values.sandboxName }}

  syncPolicy:
    syncOptions:
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    {{- if .Values.argocd.autoSync.enabled }}
    automated:
      prune: {{ .Values.argocd.autoSync.prune }}
      selfHeal: {{ .Values.argocd.autoSync.selfHeal }}
      allowEmpty: {{ .Values.argocd.autoSync.allowEmpty }}
    {{- else }}
    {{- end }}
{{- end }}
