apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.sandboxName }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.sandboxName }}-secret
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.storeName }}
    kind: {{ .Values.externalSecret.storeKind }}
  target:
    name: {{ .Values.sandboxName }}-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.externalSecret.secretPath }}
