{{- if .Values.database.enabled -}}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.sandboxName }}-pg
  namespace: {{ .Values.sandboxName }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ .Values.sandboxName }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    sandbox.deel/name: {{ .Values.sandboxName }}
spec:
  instances: {{ .Values.database.instances }}
  enablePDB: false
  imageName: "ghcr.io/cloudnative-pg/postgresql:{{ .Values.database.postgresVersion }}"

  resources:
    requests:
      memory: 128Mi
      cpu: 100m

  bootstrap:
    initdb:
      database: {{ .Values.database.bootstrapDatabase }}
      owner: {{ .Values.database.bootstrapOwner }}

  storage:
    size: {{ .Values.database.storage.size }}
    {{- if .Values.database.storage.storageClass }}
    storageClass: {{ .Values.database.storage.storageClass }}
    {{- end }}

  affinity:
    {{- if .Values.database.nodeSelector }}
    nodeSelector:
      {{- toYaml .Values.database.nodeSelector | nindent 6 }}
    {{- end }}
    {{- if .Values.database.tolerations }}
    tolerations:
      {{- toYaml .Values.database.tolerations | nindent 6 }}
    {{- end }}

  postgresql:
    pg_hba:
      - "host all all 0.0.0.0/0 md5"

  serviceAccountTemplate:
    metadata:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.s3.accountId }}:role/{{ .Values.sandboxName }}-backup-s3

  plugins:
  - name: barman-cloud.cloudnative-pg.io
    isWALArchiver: true
    parameters:
      barmanObjectName: s3-store
{{- end }}
