{{- if .Values.s3.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.sandboxName }}
  namespace: {{ .Values.sandboxName }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.s3.accountId }}:role/{{ .Values.sandboxName }}-s3
  labels:
    app.kubernetes.io/name: {{ .Values.sandboxName }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
