apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.sandboxName }}-app
  namespace: {{ .Values.sandboxName }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ .Values.sandboxName }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    sandbox.deel/name: {{ .Values.sandboxName }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ .Values.sandboxName }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
